name: Test GitHub Action

on:
  push:
    branches:
      - master
      - somik/merge-branch-test
  workflow_dispatch:  # Allows manual trigger from the Actions tab
  pull_request:
    branches:
      - somik/merge-branch-test   
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run your custom action
        uses: ./
        with:
          architecture: "-aARM64"
          os: "--os ubuntu"
          version: "--version 20.04"
          type: "--type FILE"
          path: "--path **/README.md"
